In [1]:
import numpy as np



In [2]:
# Creating a numpy array

In [4]:
x = np.array([1, 2, 3])

In [5]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[1,2,3], [1,2,3]]
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [8]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
type(1)

int

In [14]:
type(1.0)

float

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])