In [6]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [11]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(1)

array([0.78299939])

In [14]:
np.random.rand(5,5)

array([[0.223985  , 0.81617528, 0.39019822, 0.1172161 , 0.68537296],
       [0.02462972, 0.22292463, 0.83727522, 0.88376958, 0.37220954],
       [0.59610495, 0.94034216, 0.39041756, 0.55383682, 0.38407823],
       [0.83713013, 0.92662202, 0.15652233, 0.07927593, 0.95708701],
       [0.12943911, 0.7796168 , 0.01887006, 0.50552256, 0.51479554]])

In [16]:
np.random.randn(5)

array([-1.0422749 ,  1.82569808, -0.38606681,  0.59464822, -0.1491129 ])

In [19]:
np.random.randint(1, 100, 10)

array([40, 34, 96, 29, 13, 19, 32, 92, 59, 69])

In [22]:
arr = np.arange(25)
ranarr = np.random.randint(0, 50, 10)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
arr.shape

(25,)

In [28]:
ranarr

array([39, 17,  7,  6, 10, 34,  0, 27,  9, 39])

In [29]:
ranarr.argmax()

0

In [30]:
ranarr.argmin()

6

In [35]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [37]:
2 * arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [39]:
arr = np.arange(0, 11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[8]

8

In [42]:
arr[:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0, 11)
slice_of_array = arr[:5]
slice_of_array[0:2] +100

array([100, 101])

In [54]:
arr_copy = arr.copy()
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
mat = np.array([[0,10, 15], [20,25,30], [35,40,45]])
mat

array([[ 0, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
mat[0][2]

15

In [61]:
mat[0,2]

15

In [62]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
boolean_array = arr > 4
arr[boolean_array]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])